name: "nyc_tlc_trips"
version: "1.0.0"
config-version: 2

profile: "nyc_tlc_trips"

clean-targets:
  - "target"
  - "logs"

vars:
  start_date: "2022-01-01"
  end_date: "2022-04-01"

models:
  nyc_tlc_trips:
    +materialized: view

flags:
  require_generic_test_arguments_property: true
